### ISSUE TITLE
[Solved] Icon not changing on magic mirror module

### ISSUE THREAD

**Issue by wscheer** [dgonano/MMM-AlexaPi#1]
Setup:
- raspbian: jessie (full version with pixel)
- raspberry pi 2
- Installed Alexa (via https://github.com/alexa-pi/AlexaPi/)
- Usb microphone
- Using hdmi monitor speakers
- Uninstalled pulse audio to get Alexa to work

I installed the module and I'm using the default settings. I see a microphone icon with a line through it but it never changes. Alexa is running and working. I looked in the Alexa config.yaml file but I didn't see anything that I thought needed changing in the module section.

Is there anywhere I can look for errors that might help? Or maybe changing the default settings to something else?

Thanks in advance.

P.S. This Alexa project is amazing! I had a little trouble getting the audio/microphone setup but after that everything has worked pretty flawlessly.

**Comment by dgonano** [comment]
@wscheer Glad to see some interest in this module haha I think it combines the best mirror with currently the best open voice service around. 

So just to confirm, 
1. you have AlexaPi running by itself? 
2. During AlexaPi setup you chose the `magicmirror` platform and not `raspberrypi`?

That slashed microphone is the no connection symbol. If you have the two above correct can you please post your configs for the AlexaPi and the MMM-AlexaPi section of the magicmirror. 

can you also open up a web browser and go to http://raspberrypi.local:8080/alexapi?action=AVSSTATUS&status=playback
You should see a the slashed microphone change to a speaker then time out after a few seconds. Let me know if you don't. 

edit: obviously change that URL to direct to you pi properly if need be :p What your background / experience so I don't accidentally talk down to you?

**Comment by dgonano** [comment]
Also stop AlexaPi `sudo service AlexaPi stop`, run it manually in debug mode `/opt/AlexaPi/src/main.py -d` and post that output please.

**Comment by wscheer** [comment]
I'm almost certain I chose raspberry pi during the setup. I bet that's what I did wrong. I'll check it out tonight after work. Thanks for the quick reply!

**Comment by dgonano** [comment]
if so just change it in the config file and restart, it'll work fine as no specific install ins needed or it

**Comment by wscheer** [comment]
That was it! Thanks so much!

My background is I know enough to get myself into linux trouble but not enough to get back out by myself lol. Always better to provide too much info than not enough :)

**Comment by dgonano** [comment]
a good way to describe almost every linux problem I have haha 

I'm hoping to develop it a lot further so the mirror can display the GUI cards from Alexa. 
Also want to create a custom skill for the mirror so you can it it to do thinks like turn the monitor off or shutdown.

**Comment by wscheer** [comment]
That sounds awesome. When you need beta testers let me know! :)
