### ISSUE TITLE
Choppy Audio

### ISSUE THREAD

**Issue by lucallmon** [dgonano/MMM-AlexaPi#2]
I've got it working. But there are some notable bugs in the playback of audio. As soon as I log in, it says "hello" all broken. It sounds more like "lo oh." Then when it's running and I say "alexa", she sometimes says, "yes?" When I ask the question, she gives the answer broken and unreadable most of the time. Is there a fix for this?

I'm running the Raspbian Full from NOOBS install. 

Thoughts?

**Comment by lucallmon** [comment]
I overclocked my CPU to 1300MHz and it's still doing the same thing. I ask "what is the capital of china" and it tries to give me the answer, but it cuts in and out.

**Comment by dgonano** [comment]
Yeah I understand but this isn't a issue with this module, thats just an issue with AlexaPi. 
I see you have an issue open https://github.com/alexa-pi/AlexaPi/issues/157 so lets just deal with it there where others can help.
