### ISSUE TITLE
MMM-AlexaPi not showing in Magic Mirror v2.1.1

### ISSUE THREAD

**Issue by futureil** [dgonano/MMM-AlexaPi#5]
Hi dgonano

- I updated my MagicMirror to version 2.1.1
- Then I installed AlexaPi, got it working on debug mode and service mode.
- I downloaded MMM-AlexaPi, installed the module and configured the Mirror
- Configured AlexaPi tu output for 'magicmirror' instead of 'raspberrypi'

Everything is configured as it should, but for some reason the MMM-AlexaPi statuses are not being displayed in the Magic Mirror interface.

**Heartbeat responses are successful:**

`2017-04-27 21:45:39 DEBUG: Stopped play. [Errno 3] No such process`
`2017-04-27 21:45:39 DEBUG: Indicate Stop Playing`
`2017-04-27 21:45:39 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle`
`2017-04-27 21:45:39 DEBUG: Response: {"status":"success"}`
`2017-04-27 21:45:39 DEBUG: Playing audio: file:///tmp/AlexaPi-runtime-mwcsYW/WeatherPrompt.feb8f0d4-4180-4b0a-adcb-ef55688b9302_353890041.mp3
2017-04-27 21:45:39 DEBUG: Started play. sox -q /tmp/AlexaPi-runtime-mwcsYW/WeatherPrompt.feb8f0d4-4180-4b0a-adcb-ef55688b9302_353890041.mp3 -t alsa default vol -6 dB pad 0 0`
`2017-04-27 21:45:39 DEBUG: Indicate Start Playing`
`2017-04-27 21:45:39 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=playback`
`2017-04-27 21:45:39 DEBUG: Response: {"status":"success"}`
`2017-04-27 21:45:43 DEBUG: Sending MM Heatbeat`
`2017-04-27 21:45:43 DEBUG: Response: {"status":"success"}`
`2017-04-27 21:45:48 DEBUG: Sending MM Heatbeat`
`2017-04-27 21:45:48 DEBUG: Response: {"status":"success"}`
`2017-04-27 21:45:49 DEBUG: Finished play. `
`2017-04-27 21:45:49 DEBUG: Indicate Stop Playing`
`2017-04-27 21:45:49 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle`
`2017-04-27 21:45:49 DEBUG: Response: {"status":"success"}`
`2017-04-27 21:45:53 DEBUG: Sending MM Heatbeat`
`2017-04-27 21:45:53 DEBUG: Response: {"status":"success"}`

**Magic Mirror Running OK:**

`Connecting socket for: MMM-AlexaPi`
`Starting node helper for: MMM-AlexaPi`
`Connecting socket for: updatenotification`
`Connecting socket for: newsfeed`
`Starting module: newsfeed`
`Sockets connected & modules started ...`
`Fontconfig warning: ignoring UTF-8: not a valid region tag`
`Launching application.`
`Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000`

**And Alexa responding fine to commands, I can hear it and it responds well through my HDMI output.**

I don't know if this is a CSS issue or HTML displaying in Electron, I attach my debug window as well. For some reason there is no text being written within the `<i class="fa fa-microphone fa-stack-1x"></i>` element:

`<div class="container" style="display: block;"><br>`
`<div id="module_1_MMM-AlexaPi" class="module MMM-AlexaPi MMM-AlexaPi">`
`<div class="module-content">`
`<div class="normal large light">`
`<span class="fa fa-stack">`
`<i class="fa fa-microphone fa-stack-1x"></i>`
`</span></div></div></div></div>`

**Screenshot of browser inspector attaced:**

![screen shot 2017-04-27 at 9 36 03 pm](https://cloud.githubusercontent.com/assets/16654807/25512421/3df15ae2-2b93-11e7-8780-bef95a40a0e5.png)

Help will be greatly appreciated. 

Thanks a lot!

Gerardo
Mexico City

**Comment by dgonano** [comment]
Hey Gerardo, 

I don't have my system with me and won't for another couple weeks so unfortunately i can't test anything right now. 

From the logs though it all appears
* AlexaPi is running and configured correctly, reaching its endpoint 
* which means MMM-AlexaPi is running and configured correctly 

So I'm pretty sure its an issue with how the module is displayed. Normally you should see a mic with a slash through it even if there is no connection.
Could the UTF8 warming mean something?
It's in the page source so it's obviously trying to display that icon. Maybe try playing with the page source to help it display? and then in the node script that generates the xml. 
Also get another web-browser and point it to localhost:8080 or whatever your mirror address is set to so you can display it in a standard browser to rule out electron.

**Comment by dgonano** [comment]
the no text part in the xml class is how it's always been for me. Its like a special font or something `font awesome`. I just copied that part from a different module I think..

**Comment by futureil** [comment]
Hi @dgonano thanks for your reply. I have been trying to fix this with no luck, I have tried Chrome, Firefox and Safari in a separate computer but still can't see the mic icon. Maybe it is a font-awesome issue. Is there a way to replace this icon?
Thanks again!

**Comment by futureil** [comment]
I think I found where the problem is. The font awesome CSS is not being added as a style sheet of the Magic Mirror web interface. I added it by using Google Chrome's inspector:

```
<link rel="stylesheet" type="text/css" href="vendor/node_modules/font-awesome/css/font-awesome.min.css">
```
And then the Mic appeared!

How can I add this style sheet to MM by default?

Thanks a lot.

**Comment by futureil** [comment]
OK, I added it to the index.html file directly, the one in the root folder of the MagicMirror installation. Working now!
