### ISSUE TITLE
Can alexapi and magic mirror be run on the same raspberry pi?

### ISSUE THREAD

**Issue by bachoo786** [dgonano/MMM-AlexaPi#7]
Hi 

As per the title, can alexapi and magic mirror be run on the same raspberry pi?

Thanks.

**Comment by dgonano** [comment]
That is the intention. 

This is all pretty stale though, I haven't worked on it in ages

**Comment by anthony6608** [comment]
Nevermind. Rpi was running on a non-standard port.
